         BLOCK DATA
C====== HAOP PROF1 ===================================================
CXXX----KOM‹EKC "MS1" --> BEPCˆŸ 1.0  (OT „EKAPŸ 1986 ƒ.)------------
C
C                      BH“TPEHHŸŸ CTP“KT“PA
C                   TA‹ˆ–› “KA‡ATE‹E‰ MASPRT.
C                   --------------------------
C                       (COMMON /PROF1/)
C+-------+---------+------------+-------------------------------------+
CI HOMEP I ˆCO‹œ- I ‡HA—EHˆE   I  ‹Oƒˆ—ECKOE ‡HA—EHˆE “KA‡ATE‹Ÿ      I
CI ‹E-  I ‡“EMOE  I(KTO ‡A„AET)I                                     I
CI MEH-  I OO‡HA- IU - USER    I  ( [* - AAPAT PAOT› C "REGCPU" ) I
CI TA    I —EHˆE   IS - PA‡PA. I                                     I
CI MAC-  I         IPGM - POƒ. I                                     I
CI CˆBA  I         IU* - U B DR.I                                     I
C+-------+---------+------------+-------------------------------------+
CI  1    I KOD_BA0 I   PGM      I  KO„ MACCˆBA BA0 B REGION; [*       I
CI       I         I            I  (PA‡MEPHOCTœ:= NMBA0 * N1BA0)      I
CI  2    I NMBA0   I U(100)*S   I  MAX KO‹ˆ—ECTBO ‹EMEHTOB B –Eˆ;   I
CI  3    I NXBA0   I   PGM      I  KO‹ˆ—ECTBO ‹EMEHTOB B –Eˆ;       I
CI  4    I N1BA0   I  S(8)      I  KO‹-BO C‹OB MACCˆBA BA0 „‹Ÿ OˆCA- I
CI       I         I            I          HˆŸ O„HOƒO ‹EMEHTA;       I
CI  5    I KOD_KNOTI    PGM     I  KO„ MACCˆBA KNOT B REGCPU;  [*     I
CI  6    I NDKNOT  I  U(650)*S  I  PA‡MEPHOCTœ MACCˆBA KNOT;          I
CI  7    I NMKNOT  I   PGM      I  KO‹-BO “‡‹OB B PAC—ˆT›BAEMO‰ –Eˆ  I
CI       I         I            I  ( HOMEP MAX “‡‹A –Eˆ );           I
CI  8    I KOD_PAR0I   PGM      I  KO„ MACCˆBA PAR0 B REGION;  [*     I
CI  9    I NDPAR0  I U(500)*S   I  PA‡MEPHOCTœ MACCˆBA PAR0;          I
CI  10   I MODMAX  I S(100)     I  KO‹-BO PEA‹ˆ‡OBAHH›X MAKPOMO„E‹E‰; I
CI  11   I FUNMAX  I S(0)       I  KO‹-BO PEA‹ˆ‡OBAHH›X ”“HK–ˆOHA‹œ-  I
CI       I         I            I         H›X ‡ABˆCˆMOCTE‰ FUN(T);    I
CI  12   I  NRDR   I U(5)       I  HOMEP KAHA‹A CˆCTEMHOƒO BBO„A;     I
CI  13   I  NWTR   I U(3)       I  HOMEP KAHA‹A CˆCTEMHOƒO B›BO„A;    I
CI  14   I  NWTRE  I U(6)       I  HOMEP KAHA‹A ABAPˆ‰H›X B›BO„OB;    I
CI  15   I  DIAL   I U(0)*      I  0 - AKETHAŸ OPAOTKA;            I
CI       I         I            I  1 - ˆHTEPAKTˆBH›‰ PE†ˆM;           I
CI  16   I  NWTRD  I U(8)       I  HOMEP KAHA‹A B›BO„A TBEP„›X KOˆ‰; I
CI  17   I  N1MACT I S(8)       I  KO-BO C‹OB MACCˆBA MACTAB, HEOXO- I
CI       I         I            I    „ˆM›X „‹Ÿ OˆCAHˆŸ O„HO‰ MO„E‹ˆ; I
CI  18   I  NSPOOL I U(9)       I  HOMEP KAHA‹A ”A‰‹OB HAKO‹EHˆŸ;    I
CI  19   I KOD_    I   PGM      I  KO„ MACCˆBA MSWALL B REGION; [*    I
CI       I  MSWALL I            I                                     I
CI  20   I DMSWAL  I S(2000)PGM I  PA‡MEPHOCTœ MSWALL;                I
CI  21   I  NVER   I S(' 1.5')  I  HOMEP BEPCˆˆ KOM‹EKCA ( 1A4 )     I
CI  22   I KOD_    I   PGM      I  KO„ MACCˆBA YALL B REGION  [*      I
CI       I   YALL  I            I   - MATPˆ–A POBO„ˆMOCTE‰ YALL(*,*) I
CI  23   I  NDALL  I  S(50)PGM  I  ‹ˆHE‰H›E "PA‡MEPHOCTˆ" ƒP“› "ALL"I
CI  24   I KOD_    I   PGM      I  KO„ MACCˆBA JALL B REGION  [*      I
CI       I   JALL  I            I   - BEKTOP ˆCTO—HˆKOB TOKA          I
CI  25   I KOD_    I   PGM      I  KO„ MACCˆBA VALLN  B REGION  [*    I
CI       I   VALLN I            I   - BEKTOP “‡‹. HAPŸ†EHˆ‰ B T(N)   I
CI  26   I  NSYS   I   PGM      I  TEK“™AŸ PA‡MEPHOCTœ PE˜. CˆCTEM›   I
CI  27   I  KOD_   I   PGM      I  KO„ MACCˆBA LOGYTR B REGION  [*    I
CI       I  LOGYTR I            I   - BEKTOP Pˆ‡HAKOB K.‡. “‡‹OB     I
CI  28   I  ZAPROS I   PGM      I     - ‡APOC K ƒP“E DM.... HA     I
CI       I         I            I = 1   ”OPMˆPOBAHˆE YALL ˆ JALL      I
CI       I         I            I = 2   B›—ˆC‹EHˆE "HOB›X" TOKOB ˆ „P.I
CI       I         I            I = 3   AHA‹ˆ‡ CMEH› COCTOŸHˆŸ TˆP-OB.I
CI       I         I            I = 4   ˆ‡MEHEHˆE COCTOŸHˆŸ BEHTˆ‹E‰..I
CI       I         I            I = 10 ˆ 20 - CE–. B›‡OB „‹Ÿ BEHTˆ‹E‰I
CI  29   I  TN     I   PGM      I "TEK“™EE" BPEMŸ HA—A‹A HOBOƒO ˜AƒA  I
CI  30   I  H0     I   PGM      I "TEK“™ˆ‰" ˜Aƒ PAC—ETA [ 5 ‹. ƒPA„.]I
CI  31   I  MU     I U(1/2)S    I  CONST METO„A ‹ˆHE„†EPA-BˆO‹“ƒˆ    I
CI  32   I  H1     I H0*(1-MU)  I  HE ŸBH›‰ ˜Aƒ METO„A ˆHTEƒPˆPOBAHˆŸ I
CI  33   I  H2     I   H0*MU    I  ŸBH›‰ ˜Aƒ METO„A ˆHTEƒPˆPOBAHˆŸ    I
CI  34   I  FKOM   I    PGM     I  ”‹Aƒ HA‹ˆ—ˆŸ KOMM“TA–ˆ‰ B TEK. ˜AƒEI
CI  35   I  TX_G   I  PGM(-->   I  BPEMŸ ˆ‡MEHEHˆŸ TOO‹Oƒˆˆ ˆ‹ˆ COC- I
CI       I         I--> TN+H0 ) I   TOŸHˆŸ AP-OB –Eˆ := TN + HXG;   I
CI  36   I  NTX_G  I  PGM       I  HOMEP OC‹E„HEƒO ‡AKP›B˜EƒOCŸ BEHT.I
CI  37   I  FLOG   I  PGM       I  ”‹Aƒ BK‹ž—EHˆŸ AAPATA "LOGYTR".  I
CI  38   I  FSYS   I  PGM       I  ”‹Aƒ "CˆCTEMA C”OPMˆPOBAHA"(1-„A)  I
CI  39   I  EPSKOM I U(1E-6)    I  ˆHTEPBA‹ "PABH›E BPEMEHA" „‹Ÿ      I
CI       I         I            I   BPEMEHˆ KOMM“TA–ˆˆ BEHTˆ‹E‰;      I
CI  40   I  H0DATA I U(5 ‹.ƒP.)I  ‡A„AHH›‰ HA—. ˜Aƒ ˆHTEƒPˆPOBAHˆŸ.  I
CI  41   I  T5MSW  I  PGM       I  "A„P" B MSW_ALL 1-O ‹. .TˆA #5; I
CI  42   I   T0    I U(?)*      I  BPEMŸ HA—A‹A PAC—ETA-MO„E‹ˆPOBAHˆŸ.I
CI  43   I   TMAX  I U(?)*      I  BPEMŸ KOH–A  PAC—ETA-MO„E‹ˆPOBAHˆŸ.I
CI  44   I  TOUT   I  PGM       I  BPEMŸ B›BO„A C‹E„. TO—Kˆ B NSPOOL;.I
CI  45   I  FREST  I  PGM       I  ”‹Aƒ ‡APOCA "PO„O‹†ˆTœ PE˜EHˆE"; I
CI  46   I  NNTOK  I  PGM       I  KO‹-BO EPEMEHH›X, ƒP“› TOK...   I
CI  47   I  NTGRAF I  PGM       I  KO‹-BO TO—EK ƒPA”. B›BO„A;         I
CI  48   I  HOUTT  I U(H0DATA)* I  ˜Aƒ B›BO„A KOˆMO‰   ˆH”OPMA–ˆˆ.   I
CI  49   I  T6MSW  I  PGM       I  "A„P" B MSW_ALL 1-O ‹. .TˆA #6; I
CI  50   I  ZEROCP I U(1E-32)   I  "MA˜ˆHH›‰" HO‹œ...;                I
CI  51   I  KOD_   I  PGM       I  KO„ MACCˆBA VALLN1 B REGION;  [*   I
CI       I  VALLN1 I            I  -BEKTOP “‡‹OB›X HAPŸ†EHˆ‰ B TN+H0;I
CI  52   I  KOD_   I  PGM       I  KO„ MACCˆBA TOKN1 B REGION;   [*   I
CI       I   TOKN  I            I  -BEKTOP TOKOB ˆ C. EP. B TN;     I
CI  53   I  KOD_   I  PGM       I  KO„ MACCˆBA TOKN1 B REGION;   [*   I
CI       I   TOKN1 I            I  -BEKTOP TOKOB ˆ C. EP. B TN + H0;I
CI  54   I  LPRTM  I  S(200)    I  „‹ˆHA B C‹OBAX MACCˆBA MASPRT;     I
CI  55   I  FEND   I  PGM       I  ”‹Aƒ "PO–ECC PAC—ETA ‡ABEP˜EH";   I
CI  56   I  PON    I U(0)*      I  ”‹Aƒ "E—ATœ ON-LINE" 1 - „A;      I
CI  57   I  OPEN6  I  PGM       I  KO‹-BO ˆH–ˆ„EHTH›X BETBE‰ B T = TN.I
CI  58   I  KNOTM6 I  PGM       I  HOMEP MIN “‡‹A B ƒP“AX ˆH–ˆ„EHT. I
CI  59   I  GVENT6 I U(1E-5)    I  POBO„ˆMOCTœ "‡AKP›TOƒO" BEHTˆ‹Ÿ,  I
CI       I         I            I  „‹Ÿ "”ATA‹œH›X" B›PO†„EHˆ‰ CˆCTEM›;I
CI  60   I  FTEST  I U(0)       I  ”‹Aƒ TECTˆPOBAHˆŸ;                 I
CI  61   I  HXG    I  PGM       I  PEA‹œHO B›O‹HEHH›‰ ˜Aƒ:= TXG - TN;I
CI  62   I  HXMIN  I U( 0 )     I  MIN ˜Aƒ BPEMEHˆ BO‡MO†HO‰ KOM“T-–ˆˆI
CI       I         I            I  Pˆ = 0 -> "BBO„" BEHT. B HA—. HET!I
CI  63   I  SETKA  I U(90.0)*   I  CETKA O BPEMEHˆ „‹Ÿ "ƒPA”"(‹.ƒP.)I
CI  64   I  SEQTRX I U(1)       I  ”‹Aƒ "KOHTPO‹œ" B›PO†„EHHOCTˆ CˆCT.I
CI  65   I  FITER  I  PGM       I  ”‹Aƒ ‡APOC HA ˆTEPA–ˆˆ „‹Ÿ #2 ˆ #3I
CI  66   I  MITER  I U(10)      I  MAX KO‹-BO ˆTEPA–ˆ‰ HA ˜AƒE,       I
CI       I         I            I  Pˆ = 0, KOHTPO‹œ HE POBO„ˆTCŸ;   I
CI  67   I  EITER  I U(1E-3)    I  "‹OKA‹œHAŸ" „O“CTˆMAŸ O˜ˆKA->ITERI
CI  68   I  FRUNGE I U(0)       I  ”‹Aƒ "TECT P“HƒE"-> "1"/"2" ->TEST;I
CI  69   I  ERUNGE I U(1E-3)    I  "ƒ‹OA‹œHAŸ" TO—HOCTœ PAC—ETA;     I
CI  70   I  NRUNGE I U(10)      I  MAX KO‹-BO „O. "„PO‹EHˆ‰" H0DATA I
CI  71   I  SEQTIM I U(10)      I  MAX „O. KO‹-BO "CPOCOB" B TN.    I
CI  72   I  H0MIN  I U(1E-6)    I  "OƒPE˜HOCT" CETKˆ B›BO„A PE‡“‹œT. I
CI  73   I  FRCPU  I  S(0)      I  ”‹Aƒ "AAPAT" REGCPU BKž—EH;      I
CI  74   I  FMSWAL I  PGM       I  ”‹Aƒ "MSWALL" C”OPMˆPOBAH;         I
CI  75   I  KOD_   I  PGM       I  KO„ MACCˆBA XRGAF B REGION [*;     I
CI       I  XGRAF  I            I  ( C“‹ˆHƒ „‹Ÿ B›B. ƒPA”ˆKOB );     I
CI  76   I  NDX    IS(10000)PGM I  PA‡MEPHOCTœ C“‹ˆHƒA XGRAF;        I
CI  77   I  ICLOSE I U(1E-2)    I  TOK "‡AˆPAHˆŸ" BEHTˆ‹E‰;          I
CI  78   I  UOPEN  I U(1E-2)    I  HAPŸ†EHˆE "OTKP›TˆŸ" BEHTˆ‹Ÿ;     I
CI  79   I  NLITER I   PGM      I  HOMEP ‹-TA .TˆA 2 ˆ‹ˆ 3, „‹Ÿ K-OI
CI  80   I  MAXITR I   PGM      I  ‡A”ˆKCˆPOBAHA MAXITR "‹OK" O˜ˆKA; I
CI  81   I  H0OLD  I   PGM(0)   I  "CTAP›‰" TEK. ˜Aƒ ˆHTEƒ. „‹Ÿ FRUNGEI
CI  82   I  FRUN0  I   PGM      I  ‡APOC K GETNEW „‹Ÿ B›. T.P“HƒE;  I
CI  83   I  NFILER I  U(4)      I  HOMEP KAHA‹A „‹Ÿ PA. ”A‰‹A;       I
CI  84   I  NDIVH0 I   PGM(0)   I  KO‹-BO "„PO‹EHˆ‰" „‹Ÿ H0DATA;     I
CI  85   I  KOD_   I   PGM      I  KO„ PA. MACCˆBA (PA‡-Tœ NSYS)     I
CI       I   WORKX I            I   B REGION                    [*    I
CI  86   I  PONRUN I  U(0)      I  ”‹Aƒ  E—ATœ POTOKO‹A #TECT_P“HƒE#I
CI  87   I  FGMSW  I   PGM      I  "‡APOC K FM@" - “TO—HˆTœ „‹ˆH“ MSWI
CI  88   I  NSITER I   PGM      I  "CME™EHˆE" „‹Ÿ NLITER_A HOMEPA ‹.;I
CI  89   I  NMAK   I   U(1)     I  HOMEP KAHA‹A „‹Ÿ "MAKPO_PAC˜ˆPEHˆ‰"I
CI  90   I  DTCHEK I   U(0.5)*  I  ˜Aƒ O TN CO‡„AHˆŸ K.T. (B CEK.)   I
CI       I         I            I   - „O‹†HO ›Tœ KPATHOE HOUTT;      I
CI  91   I  FCHEK  I   PGM      I  ”‹Aƒ ‡APOCA HA ABTO_COXPAHEHˆE    I
CI  92   I NZAPSP  I   PGM      I  HOMEP OC‹E„HE‰ ‡AˆCˆ B NSPOOL;   I
CI  93   I T4MSW   I   PGM      I  "A„P." B MSW_ALL 1-O ‹. .TˆA #4.I
CI  94   I DTMCIU  I  U(1 ‹.ƒ) I  MIN „‹ˆT. "Cˆ“", ‡A“CKAž™EƒO BEHT.I
CI  95   I NFCHEK  I  U(10)*    I  KAHA‹ „‹Ÿ #COXP/#BOCT ->"“MO‹—AHˆE"I
CI  96   I KKCHEK  I  PGM       I  —EPE‡ KK.. TO—EK B›BO„A „E‹ATœ K.T.I
CI  97   I NFACHK  I  U(11)*    I  KAHA‹ „‹Ÿ #ACOXP -> ABTO_COXPAHEHˆEI
CI  98   I FRESTE  I   PGM      I  ”‹Aƒ #BOCT B›O‹HEHO, BCE BOCT-HO  I
CI  99   I KXXX    I   PGM      I  C.—.K. „‹Ÿ „ETEPMˆHˆPOBAHH›X B›B.  I
CI 100   I FSTD    I U(50.0)*   I  OCHOBHAŸ —ACTOTA „‹Ÿ #CEKTP ( ƒ– )I
CI 101   I DFFUR   I U(25.0)*   I  ˜Aƒ CEKTPA‹œH›X XAP-K „‹Ÿ #CEKTP I
CI 102   I F0FUR   I U(0)*      I  HA—A‹œHAŸ —ACTOTA „‹Ÿ #CEKTP (ƒ– )I
CI 103   I FMFUR   I U(975)*    I  KOHE—HAŸ  —ACTOTA „‹Ÿ #CEKTP (ƒ– )I
CI 104   I PPFUR   I U(0.5)     I  % “—ETA B(F) ˆ C(F) KO”. B #CEKTPI
CI 105   I IYSTAV  I U(1E-1)    I  TOK “CTABKˆ BEHT. ƒP“› "H—E"-3; I
CI 106   I PPVENT  I U(0)*      I  ”‹Aƒ E—ATˆ B MOMEHT KOMM“TA–ˆ‰;   I
CI 107   I METVET  I U(0)       I  # METO„A PAC—ETA TXG (HXG):        I
CI       I         I            I =0 - ˆHTEPO‹Ÿ–ˆŸ O "TN" <-> "TN1";I
CI       I         I            I =1 - EPEC—ET ˆ‡ "TN" C H0=HXG,     I
CI       I         I            I    ( HXMIN^=0 - MIN ˜Aƒ PAC—ETA );  I
CI       I         I            I =2 - "C‹ˆAHˆE" "TN1" C "TXG",      I
CI       I         I            I    (EPSKOM Pˆ TOM = ABS(TX-TN1) );I
CI       I         I            I = > 2 - TO †E, —TO ˆ =2, HO EPSKOM  I
CI       I         I            I         HE ˆ‡MEHŸETCŸ;              I
CI 108   I IPOL    I  U(0)      I ”‹Aƒ METO„A ˆHTEPO‹Ÿ–ˆˆ, =1 - CE–.I
CI 109   I KODSYS  I  U(2)      I KO„ METO„A PE˜EHˆŸ C‹A“ [Y]*[V]=[J]:I
CI       I         I            I =1 - E‡ ˆTEP. “TO—HEHˆ‰;           I
CI       I         I            I =2 - C ˆTEP. “TO—HEHˆŸMˆ->(+2 P.M.):I
CI 110   I EPSSYS  I  U(1E-6)   I TO—HOCTœ PE˜EHˆŸ "C‹A“" (KODSYS=2)  I
CI 111   I KOD_    I  PGM       I KO„ PA. MACCˆBA B REGION     [*    I
CI       I  YALLHP I            I  KOˆŸ YALL (KODSYS=2);             I
CI 112   I KOD_    I  PGM       I KO„ PA. MACCˆBA B REGION     [*    I
CI       I  WORKY  I            I  PA‡-Tœ NSYS (KODSYS=2);            I
CI 113   I KODMU   I  U(0)      I KO„ "PA‡ƒOHA" OC‹E KOMM“TA–ˆˆ:     I
CI       I         I            I =0 - "HEŸBH›‰ ‰‹EP";               I
CI       I         I            I =1 - METO„ HE MEHŸETCŸ ( ‡A„AH MU=);I
CI 114   I KODMUM  I  U(1)      I KO„ "PA‡ƒOHA" TO‹œKO „‹Ÿ ‹. MA˜.   I
CI 115   I T0OUT   I  U(0.0)    I  ç¨­ ï á T0OUT á®åà ­ïâì ¢ SPOOL   I
CI 116   I H0OUTT  I  U(0.0)    I ‘ T0OUT<>0.0 ãáâ ­®¢¨â HOUTT=H0OUTT I
CI 117   I H0DATX  I  PGM       I "­®¢ë© è £ à áç¥â " ¯®á«¥ T0OUT<>0. I
CI 118   I OUTFLG  I  PGM       I   ‚­ãâà¥­­¨© ä« £ ¤«ï T0OUT-a       I
CI 119   I INTIM   I  U(0)      I   ‘«ã¦¥¡­ë© ä« £ ¤«ï § ¯¨á¨ MSW     I
CI 120   I NSXEM   I  U(0)      I ŽŒ… ‘•…Œ› („‹Ÿ ‡€ˆ‘ˆ ŒSW ‚ ”€‰‹) I
CI 121   I FTRSPL  I  U(0)*     I ”« £ "­ «¨ç¨¥ ä¨«ìâà  ­  § ¯.SPOOL" I
CI 122   I NREGX   I  U(12)*    I ®¬¥à ª ­ «  ¤«ï #…†‡€+#…†‚Ž‘’   I
CI 123   I NEXTR   I  U(13)     I ®¬¥à ª ­ «  ¤«ï #‚…˜ ª®«-¢® â®ç¥ª I
CI 124   I NEXTRD  I  U(14)     I ®¬¥à ª ­ «  ¤«ï #‚…˜ §­ ç¥­¨ï     I
CI 125   I JNAME   IU(MS1-1989) I ˆ¬ï ä ©«  à ¡®âë: JNAME.Kxx         I
CI 126   Ichar*8   I            I xx - ­®¬¥à ª ­ «  ¢¢®¤ /¢ë¢®¤       I
CI 127   I NZRDR   I    PGM(0)  I ‘ª®«ìª® à § ç¨â «¨ § ¯. ¨§ NRDR     I
CI 128   I FLGDIG  I   PGM(0)   I =0 - #‘—…’:  = 1 - #‘—…’           I
CI 129   I FLGCIR  I   PGM(0)   I =0 - #–…œ:  = 1 - #•–…œ           I
CI       I         I            I                                     I
CI       I         I            I                                     I
CI       I         I            I                                     I
C+-------+---------+------------+-------------------------------------+
CZZZ-------------------------------------------------------------------
         COMMON /PROF1/ MASPRT(200)
C----------------------------------------------------------------------
         DATA MASPRT/ 200 * 0 /
C----------------------------------------------------------------------
       END
