         BLOCK DATA
C=====>  SERVZ1  <=====================================================
CXXX----KOM‹EKC "MS1" --> BEPCˆŸ 1.0  (OT „EKAPŸ 1986 ƒ.)-----------+
C                                                                     I
C           TA‹ˆ–A CME™EHˆ‰ MACCˆBA TOKN ( TOKN1 )  TABSPC.          I
C               ( COMMON / SERVZ1 / TABSPC(1)  )                      I
C                                                                     I
C+--------+-----------+---------------+------------+------------------+
CI HOMEP  I KO„ ˆMEHˆ I „O. CME™EHˆŸ I KO„ ˆMEHˆ  I   PˆME—AHˆE     I
CI TˆA   I  TˆA     I-------+-------I EPEMEHHO‰ I                  I
CI MO„E‹ˆ I MO„E‹ˆ    I "OT"  I  "„O" I            I                  I
C+--------+-----------+-------+-------+------------+------------------+
CI   1    I    2      I   3   I   4   I     5      I                  I
C+--------+-----------+-------+-------+------------+-------------------
CI   1    I   1       I 1     I  1    I   1        I R, TOK           I
CI   2    I   2       I 1     I  1    I   1        I L, TOK           I
CI   3    I   3       I 1     I  1    I   1        I C, TOK           I
CI   4    I   4       I 1     I  1    I   1        I J, TOK           I
CI   5    I   5       I 1     I  1    I   1        I E, TOK           I
CI   6    I   6       I 1     I  1    I   1        I E_SIN, TOK       I
CI   7    I   6       I 1     I  1    I   1        I E_SIN, TOK       I
CI   8    I   8       I 1     I  1    I   1        I HE “P. BEHT.,TOKI
CI   9    I   9       I 1     I  1    I   1        I “P. BEHT.,TOK   I
CI   9    I   9       I 2     I  2    I   6        I  --//--, Cˆƒ.“P.I
CI   90   I   -9      I 0     I  0    I   0        I CM. # 9          I
CI   10   I   10      I 1     I  11   I   1        I MOCT ‹APˆOHOBA   I
CI   10   I   10      I 12    I  17   I   6        I  --//--, Cˆƒ.“P.I
CI   100  I  -10      I 0     I  0    I   0        I CM. # 10         I
CI   11   I   11      I 1     I  6    I   1        I ‹.MA˜.3X3X0, TOKI
CI   11   I   11      I 7     I  7    I   2        I -/- , GAMMA      I
CI   11   I   11      I 8     I  8    I   3        I -/- , OMEGA      I
CI   11   I   11      I 9     I  9    I   4        I -/- , MM.       I
CI   11   I   11      I 10    I  10   I   5        I -/- , MBH.       I
CI   110  I   -11     I 0     I  0    I   0        I CM. # 11         I
CI   12   I   -11     I 0     I  0    I   0        I CM. # 11         I
CI   120  I   -11     I 0     I  0    I   0        I CM. # 11         I
CI   80   I    7      I 1     I  1    I   1        I HE “P. RL BEHT. I
CI   81   I    12     I 1     I  1    I   1        I “P. RL BEHT.    I
CI   81   I    12     I 2     I  2    I   6        I  --//--, Cˆƒ.“P.I
CI  666   I    14     I 1     I  1    I   1        I  K‹ž— (PE‹E), TOKI
CI  666   I    14     I 2     I  2    I   6        I  --//--, Cˆƒ.“P.I
CI   22   I    15     I 1     I  2    I   1        I 2-X OM.TP-P, TOKI
CI   23   I    15     I 1     I  3    I   1        I 3-X OM.TP-P, TOKI
CI   24   I    15     I 1     I  4    I   1        I 4-X OM.TP-P, TOKI
CI   25   I    15     I 1     I  5    I   1        I 5-X OM.TP-P, TOKI
CI   26   I    15     I 1     I  6    I   1        I 6-X OM.TP-P, TOKI
CI   71   I    16     I 1     I  1    I   1        I HE‹. R, TOK,     I
CI   72   I    17     I 1     I  1    I   1        I HE‹. L, TOK,     I
CI  720   I   -72     I 0     I  0    I   0        I HE‹. L-> L_„ˆ”.  I
CI   40   I    18     I 1     I  3    I   7        I PEƒ. BO‡. U_“P.I
CI   40   I    18     I 4     I  4    I   8        I =/=,OMEƒA CˆCTEM›I
CI   40   I    18     I 5     I  5    I   9        I =/=, CKO‹œ†EHˆE  I
CI   40   I    18     I 6     I  6    I   10       I =/=, U_“P. Q_CˆHI
CI   40   I    18     I 7     I  7    I   11       I =/=, U_“P. D_CˆHI
CI   40   I    18     I 8     I  8    I   19       I =/=, U_S_Q_O._00I
CI   40   I    18     I 9     I  9    I   20       I =/=, U_S_D_O._00I
CI   40   I    18     I 10    I  10   I   21       I =/=, I_S_Q_O._00I
CI   40   I    18     I 11    I  11   I   22       I =/=, I_S_D_O._00I
CI   40   I    18     I 12    I  12   I   23       I =/=, U_R_Q_O._00I
CI   40   I    18     I 13    I  13   I   24       I =/=, U_R_D_O._00I
CI   40   I    18     I 14    I  14   I   25       I =/=, I_R_Q_O._00I
CI   40   I    18     I 15    I  15   I   26       I =/=, I_R_D_O._00I
CI   40   I    18     I 16    I  16   I   30       I =/=, ISD_ZAD_O. I
CI   40   I    18     I 17    I  17   I   31       I =/=,  S _ ZAD.   I
CI   40   I    18     I 18    I  18   I   32       I =/=, INT(TOK).   I
CI   40   I    18     I 19    I  19   I   33       I =/=, INT( S ).   I
CI   40   I    18     I 20    I  20   I   13       I =/=, PE‡EPB      I
CI   50   I    19     I 1     I  6    I   1        I H—E3, B›X. TOKˆ I
CI   50   I    19     I 7     I  24   I   12       I =/=, TOKˆ BEHT.  I
CI   50   I    19     I 25    I  42   I   6        I =/=, Cˆ“ CˆƒHA‹›.I
CI   63   I    21     I 1     I  4    I   1        I E_SIN_3, TOK     I
CI   13   I    20     I 1     I  3    I   14       I „AT—ˆK V, HAPŸ†.I
CI   13   I    20     I 4     I  4    I   15       I =/=, V_MO„“‹œ    I
CI   13   I    20     I 5     I  5    I   16       I =/=, “ƒO‹ C ”."A"I
CI   13   I    20     I 6     I  6    I   17       I =/=, V_X HA "A". I
CI   13   I    20     I 7     I  7    I   18       I =/=, V_Y HA A+90ƒI
CI   13   I    20     I 8     I  8    I   28       I =/=, OMEƒA ->ABC I
CI  667   I  -666     I 0     I  0    I    0       I K‹ž—-PE‹E-> # 666I
CI   64   I    22     I 1     I  4    I    1       I E_PEƒ. BO‡. TOK  I
CI   64   I    22     I 5     I  7    I   27       I =/=, .„.C. B›X. I
CI   92   I    23     I 1     I  1    I    1       I BEHT.K‹ž—, TOK   I
CI   92   I    23     I 2     I  3    I   12       I =/=, TOK BEHTˆ‹Ÿ.I
CI   92   I    23     I 4     I  5    I    6       I =/=, Cˆƒ. "Cˆ“"  I
CI   14   I   -11     I 0     I  0    I   0        I CM. # 11         I
CI   140  I   -11     I 0     I  0    I   0        I CM. # 11         I
CI   93   I    24     I 1     I  1    I   1        I “P. BEHT.,TOK   I
CI   93   I    24     I 2     I  2    I   6        I ====/==== ,Cˆ“   I
CI  502   I    25     I 1     I  2    I   1        I ˜Aƒ.„BˆƒATE‹œ,TOKI
CI  502   I    25     I 3     I  3    I   2        I ˜„,GAMMA         I
CI  502   I    25     I 4     I  4    I   3        I ˜„,OMEGA         I
CI  502   I    25     I 5     I  5    I   4        I ˜„,‹.MAƒ.MOMEHT I
CI  502   I    25     I 6     I  6    I   5        I ˜„, BHE˜. MOMEHT I
CI  503   I    25     I 1     I  3    I   1        I ˜Aƒ.„BˆƒATE‹œ,TOKI
CI  503   I    25     I 4     I  4    I   2        I ˜„,GAMMA         I
CI  503   I    25     I 5     I  5    I   3        I ˜„,OMEGA         I
CI  503   I    25     I 6     I  6    I   4        I ˜„,‹.MAƒ.MOMEHT I
CI  503   I    25     I 7     I  7    I   5        I ˜„, BHE˜. MOMEHT I
CI  504   I    25     I 1     I  4    I   1        I ˜Aƒ.„BˆƒATE‹œ,TOKI
CI  504   I    25     I 5     I  5    I   2        I ˜„,GAMMA         I
CI  504   I    25     I 6     I  6    I   3        I ˜„,OMEGA         I
CI  504   I    25     I 7     I  7    I   4        I ˜„,‹.MAƒ.MOMEHT I
CI  504   I    25     I 8     I  8    I   5        I ˜„, BHE˜. MOMEHT I
CI  505   I    25     I 1     I  5    I   1        I ˜Aƒ.„BˆƒATE‹œ,TOKI
CI  505   I    25     I 6     I  6    I   2        I ˜„,GAMMA         I
CI  505   I    25     I 7     I  7    I   3        I ˜„,OMEGA         I
CI  505   I    25     I 8     I  8    I   4        I ˜„,‹.MAƒ.MOMEHT I
CI  505   I    25     I 9     I  9    I   5        I ˜„, BHE˜. MOMEHT I
CI  506   I    25     I 1     I  6    I   1        I ˜Aƒ.„BˆƒATE‹œ,TOKI
CI  506   I    25     I 7     I  7    I   2        I ˜„,GAMMA         I
CI  506   I    25     I 8     I  8    I   3        I ˜„,OMEGA         I
CI  506   I    25     I 9     I  9    I   4        I ˜„,‹.MAƒ.MOMEHT I
CI  506   I    25     I 10    I  10   I   5        I ˜„, BHE˜. MOMEHT I
CI  507   I    25     I 1     I  7    I   1        I ˜Aƒ.„BˆƒATE‹œ,TOKI
CI  507   I    25     I 8     I  8    I   2        I ˜„,GAMMA         I
CI  507   I    25     I 9     I  9    I   3        I ˜„,OMEGA         I
CI  507   I    25     I 10    I  10   I   4        I ˜„,‹.MAƒ.MOMEHT I
CI  507   I    25     I 11    I  11   I   5        I ˜„, BHE˜. MOMEHT I
CI  508   I    25     I 1     I  8    I   1        I ˜Aƒ.„BˆƒATE‹œ,TOKI
CI  508   I    25     I 9     I  9    I   2        I ˜„,GAMMA         I
CI  508   I    25     I 10    I  10   I   3        I ˜„,OMEGA         I
CI  508   I    25     I 11    I  11   I   4        I ˜„,‹.MAƒ.MOMEHT I
CI  508   I    25     I 12    I  12   I   5        I ˜„, BHE˜. MOMEHT I
CI  512   I    25     I 1     I  2    I   1        I ˜Aƒ.„BˆƒATE‹œ,TOKI
CI  512   I    25     I 3     I  3    I   34       I ˜„,EPEME™EHˆE   I
CI  512   I    25     I 4     I  4    I   35       I ˜„,‹ˆH.CKOPOCTœ  I
CI  512   I    25     I 5     I  5    I   36       I ˜„,‹.MAƒ.Cˆ‹A   I
CI  512   I    25     I 6     I  6    I   37       I ˜„, BHE˜. Cˆ‹A   I
CI  513   I    25     I 1     I  3    I   1        I ˜Aƒ.„BˆƒATE‹œ,TOKI
CI  513   I    25     I 4     I  4    I   34       I ˜„,EPEME™EHˆE   I
CI  513   I    25     I 5     I  5    I   35       I ˜„,‹ˆH.CKOPOCTœ  I
CI  513   I    25     I 6     I  6    I   36       I ˜„,‹.MAƒ.Cˆ‹A   I
CI  513   I    25     I 7     I  7    I   37       I ˜„, BHE˜. Cˆ‹A   I
CI  514   I    25     I 1     I  4    I   1        I ˜Aƒ.„BˆƒATE‹œ,TOKI
CI  514   I    25     I 5     I  5    I   34       I ˜„,EPEME™EHˆE   I
CI  514   I    25     I 6     I  6    I   35       I ˜„,‹ˆH.CKOPOCTœ  I
CI  514   I    25     I 7     I  7    I   36       I ˜„,‹.MAƒ.Cˆ‹A   I
CI  514   I    25     I 8     I  8    I   37       I ˜„, BHE˜. Cˆ‹A   I
CI  515   I    25     I 1     I  5    I   1        I ˜Aƒ.„BˆƒATE‹œ,TOKI
CI  515   I    25     I 6     I  6    I   34       I ˜„,EPEME™EHˆE   I
CI  515   I    25     I 7     I  7    I   35       I ˜„,‹ˆH.CKOPOCTœ  I
CI  515   I    25     I 8     I  8    I   36       I ˜„,‹.MAƒ.Cˆ‹A   I
CI  515   I    25     I 9     I  9    I   37       I ˜„, BHE˜. Cˆ‹A   I
CI  516   I    25     I 1     I  6    I   1        I ˜Aƒ.„BˆƒATE‹œ,TOKI
CI  516   I    25     I 7     I  7    I   34       I ˜„,EPEME™EHˆE   I
CI  516   I    25     I 8     I  8    I   35       I ˜„,‹ˆH.CKOPOCTœ  I
CI  516   I    25     I 9     I  9    I   36       I ˜„,‹.MAƒ.Cˆ‹A   I
CI  516   I    25     I 10    I  10   I   37       I ˜„, BHE˜. Cˆ‹A   I
CI  517   I    25     I 1     I  7    I   1        I ˜Aƒ.„BˆƒATE‹œ,TOKI
CI  517   I    25     I 8     I  8    I   34       I ˜„,EPEME™EHˆE   I
CI  517   I    25     I 9     I  9    I   35       I ˜„,‹ˆH.CKOPOCTœ  I
CI  517   I    25     I 10    I  10   I   36       I ˜„,‹.MAƒ.Cˆ‹A   I
CI  517   I    25     I 11    I  11   I   37       I ˜„, BHE˜. Cˆ‹A   I
CI  518   I    25     I 1     I  8    I   1        I ˜Aƒ.„BˆƒATE‹œ,TOKI
CI  518   I    25     I 9     I  9    I   34       I ˜„,EPEME™EHˆE   I
CI  518   I    25     I 10    I  10   I   35       I ˜„,‹ˆH.CKOPOCTœ  I
CI  518   I    25     I 11    I  11   I   36       I ˜„,‹.MAƒ.Cˆ‹A   I
CI  518   I    25     I 12    I  12   I   37       I ˜„, BHE˜. Cˆ‹A   I
CI  301   I    26     I  1    I   6   I   38       I Cˆ”“, KO„ Cˆ“    I
CI  301   I    26     I  7    I  12   I   39       I Cˆ”“, ˜Aƒ ˆ‡M.Cˆ“I
CI  668   I    27     I  1    I   1   I    1       I K‹ž—,“P.Cˆ”“,TOKI
CI  668   I    27     I  2    I   2   I    6       I K‹ž—,“P.Cˆ”“,Cˆ“I
CI  310   I    28     I  1    I   1   I   40       I -PEƒ“‹.,B›X.Cˆƒ.I
CI  311   I    29     I  1    I   1   I   40       I ˆ-PEƒ“‹.,B›X.Cˆƒ.I
CI  312   I    30     I  1    I   1   I   40       I ˆH.‡BEH.,B›X.Cˆƒ.I
CI  313   I    31     I  1    I   1   I   40       I „-PEƒ“‹.,B›X.Cˆƒ.I
CI  314   I    34     I  1    I   1   I   40       I ˆ-PEƒ. ,B›X.Cˆƒ.I
CI  315   I    35     I  1    I   1   I   40       I „-PEƒ. ,B›X.Cˆƒ.I
CI  316   I    36     I  1    I   1   I   40       I ”A‡OBP. ,B›X.Cˆƒ.I
CI  317   I    37     I  1    I   1   I   40       I KO‹.‡BEHO,B›X.CˆƒI
CI  318   I    28     I  1    I   1   I   40       I -PEƒ“‹. ,B›X.CˆƒI
CI  320   I    38     I  1    I   1   I   40       I HE‹.‡BEHO,B›X.CˆƒI
CI  321   I    39     I  1    I   1   I   40       I PE‹.‡BEHO,B›X.CˆƒI
CI  322   I    40     I  1    I   1   I   40       I ‡BEHO"—‡",B›X.CˆƒI
CI  323   I    41     I  1    I   1   I   40       I “MHO†ˆT. ,B›X.CˆƒI
CI  324   I  -318     I  0    I   0   I    0       I -PEƒ“‹. ,B›X.CˆƒI
CI   17   I    33     I  1    I   1   I    1       I “P.ˆCT.TOKA,TOK I
CI   17   I    33     I  2    I   2   I   41       I “P.ˆCT.TOKA,P   I
CI   17   I    33     I  3    I   3   I   42       I “P.ˆCT.TOKA,Q   I
CI   15   I    42     I  1    I   1   I    1       I ˆT“H,TOK         I
CI   16   I    43     I  1    I   1   I    1       I ˆH“H,TOK         I
CI  200   I    44     I  1    I   2   I    1       I ˆ„.O.“Cˆ‹ˆT.,TOKI
CI  330   I    45     I  1    I   2   I   40       I ‹."ˆ",B›X.CˆƒH. I
CI  330   I    45     I  3    I   3   I   43       I ‹."ˆ",BPEMŸ TX  I
CI  331   I    46     I  1    I   2   I   40       I ‹."ˆ‹ˆ",B›X.Cˆƒ.I
CI  331   I    46     I  3    I   3   I   43       I ‹."ˆ‹ˆ",BPEMŸ TXI
CI  332   I    47     I  1    I   2   I   40       I ‹."ˆCK‹.ˆ‹ˆ",B›XI
CI  332   I    47     I  3    I   3   I   43       I ‹."ˆCK‹.ˆ‹ˆ",BPMI
CI  333   I    48     I  1    I   2   I   40       I RS-TPˆƒ.,B›X.Cˆƒ.I
CI  333   I    48     I  3    I   3   I   43       I RS-TPˆƒ.,BPEMŸ TXI
CI  334   I    49     I  1    I   2   I   40       I  D-TPˆƒ.,B›X.Cˆƒ.I
CI  334   I    49     I  3    I   3   I   43       I  D-TPˆƒ.,BPEMŸ TXI
CI  335   I    50     I  1    I   2   I   40       I JK-TPˆƒ.,B›X.Cˆƒ.I
CI  335   I    50     I  3    I   3   I   43       I JK-TPˆƒ.,BPEMŸ TXI
CI  360   I    51     I  1    I   2   I   40       I KOMAP.,B›X.CˆƒH.I
CI  360   I    51     I  3    I   3   I   43       I KOMAP.,BPEMŸ TX I
CI  361   I  -360     I  0    I   0   I    0       I KOMAP.,KAK #360 I
CI   18   I    53     I  1    I   9   I    1       I 3-X ”.KOMEHC.TOKI
CI  520   I    52     I  1    I   1   I    1       I „T,TOK          I
CI  520   I    52     I  2    I   2   I    2       I „T,GAMMA        I
CI  520   I    52     I  3    I   3   I    3       I „T,OMEGA        I
CI  520   I    52     I  4    I   4   I    5       I „T,MBH(T)       I
CI  520   I    52     I  5    I   5   I    1       I „T,TOK Tƒ.      I
CI  521   I  -520     I  0    I   0   I    0       I TAK†E KAK #520   I
CI   65   I    21     I  1    I   4   I    1       I E-SIN, TOK       I
CI   32   I    15     I  1    I   3   I    1       I TP-P , TOK       I
CI   33   I    15     I  1    I   4   I    1       I TP-P , TOK       I
CI  325   I    54     I  1    I   1   I   40       I KB.KOPEHœ,B›X.CˆƒI
CI   36   I    15     I  1    I   9   I    1       I TP-P , TOK       I
CI 319    I    55     I  1    I   1   I    40      I ƒEHEP.ˆ‹.Cˆƒ,B›XI
CI 380    I    57     I  1    I   8   I    44      I POH MˆKPOPO–ECC.I
CI 380    I    57     I  9    I   9   I    45      I CC MˆKPOPO–ECC.I
CI 380    I    57     I  10   I   10  I    46      I CO„EP.OPTA B/B  I
CI 380    I    57     I  11   I   11  I    43      I BPEMŸ ˆ‡MEH.OPTAI
CI 999    I    58     I  1    I   30  I    47      I MEX.,OO™.KOOP„.I
CI  73    I   -71     I   0   I   0   I    0       I RN,TOK           I
CI 800    I    59     I   1   I   1   I    14      I K TOKˆ          I
CI  66    I     6     I   1   I   1   I    1       I E_SIN, TOK       I
CI  67    I    32     I   1   I   1   I    1       I J_SIN, TOK       I
CI  42    I   -22     I   0   I   0   I    0       I ’€‘”ŽŒ€’Ž    I
CI  43    I   -23     I   0   I   0   I    0       I ’€‘”ŽŒ€’Ž    I
CI  44    I   -24     I   0   I   0   I    0       I ’€‘”ŽŒ€’Ž    I
CI  45    I   -25     I   0   I   0   I    0       I ’€‘”ŽŒ€’Ž    I
CZZZ-------------------------------------------------------------------
         COMMON /SERVZ1/ TABSPC(1200)
C-->  HA ®¤¨­ ¬ áá¨¢ 100 í«. = 20 ®¯¨á ­¨© = 10 áâà®ç¥ª****************
        DIMENSION TABS01(100)
        DIMENSION TABS02(100)
        DIMENSION TABS03(100)
        DIMENSION TABS04(100)
        DIMENSION TABS05(100)
        DIMENSION TABS06(100)
        DIMENSION TABS07(100)
        DIMENSION TABS08(100)
        DIMENSION TABS09(100)
        DIMENSION TABS10(100)
        DIMENSION TABS11(100)
        DIMENSION TABS12(100)
C
        EQUIVALENCE( TABSPC(0001),   TABS01(1) )
        EQUIVALENCE( TABSPC(0101),   TABS02(1) )
        EQUIVALENCE( TABSPC(0201),   TABS03(1) )
        EQUIVALENCE( TABSPC(0301),   TABS04(1) )
        EQUIVALENCE( TABSPC(0401),   TABS05(1) )
        EQUIVALENCE( TABSPC(0501),   TABS06(1) )
        EQUIVALENCE( TABSPC(0601),   TABS07(1) )
        EQUIVALENCE( TABSPC(0701),   TABS08(1) )
        EQUIVALENCE( TABSPC(0801),   TABS09(1) )
        EQUIVALENCE( TABSPC(0901),   TABS10(1) )
        EQUIVALENCE( TABSPC(1001),   TABS11(1) )
        EQUIVALENCE( TABSPC(1101),   TABS12(1) )
C-->
        INTEGER TABSPC,TABS01,TABS02,TABS03,TABS04,TABS05,TABS06
        INTEGER        TABS07,TABS08,TABS09,TABS10,TABS11,TABS12
C++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
         DATA TABS01/ 1,1,1,1,1,          2,2,1,1,1,
     2                3,3,1,1,1,          4,4,1,1,1,
     3                5,5,1,1,1,          6,6,1,1,1,
     4                8,8,1,1,1,          9,9,1,1,1,
     5                9,9,2,2,6,          90,-9,0,0,0,
     6               10,10,1,11,1,        10,10,12,17,6,
     7               100, -10, 0,0,0,     11, 11, 1, 6, 1,
     8               11,11,7,7,2,         11,11,8,8,3,
     9               11,11,9,9,4,         11,11,10,10,5,
     +               110, -11,0,0,0,      12, -11, 0,0,0/
C
        DATA TABS02/120, -11,0,0,0,       80,7,1,1,1,
     2                81, 12, 1,1,1,      81,12,2,2,6,
     3               666, 14, 1,1,1,      666, 14, 2,2,6,
     4               22, 15,1,2,1,        23,15,1,3,1,
     5               24, 15,1,4,1,        25,15,1,5,1,
     6               26,15,1,6,1,         71,16,1,1,1,
     7               72,17,1,1,1,         40,18,1,3,7,
     8               40,18,4,4,8,         40,18,5,5,9,
     9               40,18,6,6,10,        40,18,7,7,11,
     +               40,18,8,8,19,        40,18,9,9,20/
C
        DATA TABS03/ 40,18,10,10,21,     40,18,11,11,22,
     2               40,18,12,12,23,  40,18,13,13,24,  40,18,14,14,25,
     3               40,18,15,15,26,  40,18,16,16,30,  40,18,17,17,31,
     4               40,18,18,18,32,  40,18,19,19,33,
     5               40,18,20,20,13, 50,19,1,6,1,     50,19,7,24,12,
     6               50,19,25,42,6,   63,21,1,4,1,     13,20,1,3,14,
     7               13,20,4,4,15,    13,20,5,5,16,    13,20,6,6,17,
     +               13,20,7,7,18/
C
        DATA TABS04/ 13,20,8,8,28,  720,-72,0,0,0,   667,-666,0,0,0,
     2               64,22,1,4,1,    64,22,5,7,27,
     3               92,23,1,1,1,  92,23,2,3,12,  92,23,4,5,6,
     4                14,-11,0,0,0,   140,-11,0,0,0,
     5              93,24,1,1,1,  93,24,2,2,6,
     6  502,25,1,2,1,   502,25,3,3,2,   502,25,4,4,3,   502,25,5,5,4,
     +  502,25,6,6,5,   503,25,1,3,1,   503,25,4,4,2,   503,25,5,5,3/
C
        DATA TABS05/    503,25,6,6,4,   503,25,7,7,5,
     2  504,25,1,4,1,   504,25,5,5,2,   504,25,6,6,3,   504,25,7,7,4,
     3  504,25,8,8,5,
     4  505,25,1,5,1,   505,25,6,6,2,   505,25,7,7,3,
     5                  505,25,8,8,4,   505,25,9,9,5,
     6  506,25,1,6,1,   506,25,7,7,2,   506,25,8,8,3,   506,25,9,9,4,
     7  506,25,10,10,5,
     +  507,25,1,7,1,   507,25,8,8,2,   507,25,9,9,3/
C
        DATA TABS06/    507,25,10,10,4,   507,25,11,11,5,
     2  508,25,1,8,1,   508,25,9,9,2,   508,25,10,10,3, 508,25,11,11,4,
     3  508,25,12,12,5,
     4  512,25,1,2,1,   512,25,3,3,34,  512,25,4,4,35,
     5                   512,25,5,5,36,  512,25,6,6,37,
     6  513,25,1,3,1,   513,25,4,4,34,  513,25,5,5,35,  513,25,6,6,36,
     7  513,25,7,7,37,
     +  514,25,1,4,1,   514,25,5,5,34,  514,25,6,6,35 /
C======================================================================
        DATA  TABS07/    514,25,7,7,36,  514,25,8,8,37,
     =  515,25,1,5,1,   515,25,6,6,34,  515,25,7,7,35,  515,25,8,8,36,
     =  515,25,9,9,37,
     =  516,25,1,6,1,   516,25,7,7,34,  516,25,8,8,35,  516,25,9,9,36,
     =  516,25,10,10,37,
     =  517,25,1,7,1,   517,25,8,8,34,  517,25,9,9,35,  517,25,10,10,36,
     =  517,25,11,11,37,
     =  518,25,1,8,1,   518,25,9,9,34, 518,25,10,10,35/
        DATA  TABS08/     518,25,11,11,36,
     =  518,25,12,12,37,               301,26,1,6,38,   301,26,7,12,39,
     =  668,27,1,1,1,   668,27,2,2,6,  310,28,1,1,40,   311,29,1,1,40,
     =  312,30,1,1,40,  313,31,1,1,40,   7,6,1,1,1,     17,33,1,1,1,
     =   17,33,2,2,41,   17,33,3,3,42, 314,34,1,1,40,  315,35,1,1,40,
     =  316,36,1,1,40,  317,37,1,1,40, 320,38,1,1,40,  321,39,1,1,40/
C======================================================================
        DATA TABS09/    322,40,1,1,40,  323,41,1,1,40,   15,42,1,1,1,
     =   16,43,1,1,1,   200,44,1,2,1,   330,45,1,2,40,  330,45,3,3,43,
     =  331,46,1,2,40,  331,46,3,3,43,  332,47,1,2,40,  332,47,3,3,43,
     =  333,48,1,2,40,  333,48,3,3,43,  334,49,1,2,40,  334,49,3,3,43,
     =  335,50,1,2,40,  335,50,3,3,43,  360,51,1,2,40,  360,51,3,3,43,
     =  361,-360,0,0,0/
        DATA TABS10/    18,53,1,9,1,   318,28,1,1,40,  520,52,1,1,1,
     =  520,52,2,2,2,   520,52,3,3,3,   520,52,4,4,5,   520,52,5,5,1,
     =  521,-520,0,0,0,  65,21,1,4,1,    32,15,1,3,1,    33,15,1,4,1,
     =  324,-318,0,0,0, 325,54,1,1,40,   36,15,1,9,1,   319,55,1,1,40,
     =  380,57,1,8,44, 380,57,9,9,45, 380,57,10,10,46,380,57,11,11,43,
     =  999,58,1,30,47  /
C======================================================================
        DATA TABS11/     73,16,1,1,1,   800,59,1,1,14,   66,6,1,1,1,
     =   67,32,1,1,1,   42,-22,0,0,0,    43,-23,0,0,0,   44,-24,0,0,0,
     =   45,-25,0,0,0,   000,00,0,0,0,   000,00,0,0,00,  000,00,0,0,00,
     =  000,00,0,0,0,   000,00,0,0,0,   000,00,0,0,00,  000,00,0,0,00,
     =  000,00,0,0,0,   000,00,0,0,0,   000,00,0,0,00,  000,00,0,0,00,
     =  000,00,0,0,0/
        DATA TABS12/    000,00,0,0,0,   000,00,0,0,00,  000,00,0,0,00,
     =  000,00,0,0,0,   000,00,0,0,0,   000,00,0,0,00,  000,00,0,0,00,
     =  000,00,0,0,0,   000,00,0,0,0,   000,00,0,0,00,  000,00,0,0,00,
     =  000,00,0,0,0,   000,00,0,0,0,   000,00,0,0,00,  000,00,0,0,00,
     =  000,00,0,0,0,   000,00,0,0,0,   000,00,0,0,00,  000,00,0,0,00,
     =  000,00,0,00,00  /
C++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
         END
