         BLOCK DATA
C===>  SERVZ3  <=======================================================
CXXX----KOM‹EKC "MS1" --> BEPCˆŸ 1.0  (OT „EKAPŸ 1986 ƒ.)------------
C
C           TA‹ˆ–A ˆMEH MAKPOMO„E‹E‰ "TABTIP"
C          COMMON / SERVZ3 /  TABTIP(1)
C
C+--------------+----------------------------------+
CI A„PEC BXO„A  I      ˆMŸ MO„E‹ˆ                  I
CI              I                                  I
CI KO„ ˆMEHˆ    I [ „‹ˆHA CTPOKˆ 5 C‹OB ]          I
CI  MO„E‹ˆ      I   XPAHEHˆE ‹OTHOE  (20 CˆMBO‹OB)I
C+--------------+----------------------------------+
CI              I    5   C‹OB  B  CTPOKE           I
C+--------------+----------------------------------+
CI   1          I  COPOTˆB‹EHˆE                   I
CI   2          I  ˆH„“KTˆBHOCTœ                   I
CI   3          I  EMKOCTœ                         I
CI   4          I  ˆCTO—HˆK OCTOŸHHOƒO TOKA       I
CI   5          I  .„.C. OCTOŸHHAŸ               I
CI   6          I  .„.C. SIN - AŸ.                I
CI   7          I  RL - „ˆO„                       I
CI   8          I  „ˆO„                            I
CI   9          I  BEHTˆ‹œ                         I
CI   10         I  MOCT ‹APˆOHOBA                  I
CI   11         I  ‹. MA˜ˆHA 3X3X0                I
CI   12         I  RL - BEHTˆ‹œ                    I
CI   13         I  [??]                            I
CI   14         I  ˆ„EA‹œH›‰ K‹ž— (PE‹E)           I
CI   15         I  TPAHC”OPMATOP                   I
CI   16         I  HE‹ˆHE‰HOE COPOTˆB‹EHˆE        I
CI   17         I  HE‹ˆHE‰HAŸ ˆH„“KTˆBHOCTœ        I
CI   18         I  PEƒ“‹ŸTOP BO‡“†„EHˆŸ 3X3X0     I
CI   19         I  BO‡“„ˆTE‹œ 3X3X0 H—E 3”-HO‰   I
CI   20         I  „AT—ˆK HAPŸ†EHˆŸ               I
CI   21         I  .„.C. 3-X ”A‡HAŸ SIN-Ÿ         I
CI   22         I  .„.C. PEƒ“‹ŸTOPA BO‡“†„EHˆŸ   I
CI   23         I  BEHTˆ‹œH›‰ K‹ž—                 I
CI   24         I  BEHTˆ‹œ, “PAB‹ŸEM›‰ Cˆ”“       I
CI   25         I  ˜AƒOB›‰ „BˆƒATE‹œ               I
CI   26         I  Cˆ”“                            I
CI   27         I  K‹ž— , “PAB‹ŸEM›‰ Cˆ”“         I
CI   28         I   - PEƒ“‹ŸTOP                   I
CI   29         I  ˆ - PEƒ“‹ŸTOP                   I
CI   30         I  ˆHEP–ˆOHHOE ‡BEHO               I
CI   31         I  „ - PEƒ“‹ŸTOP                   I
CI   32         I  J  SIN - HAŸ                    I
CI   33         I  J  “PAB‹. / O‹œ‡OBATE‹Ÿ     I
CI   34         I  ˆ - PEƒ“‹ŸTOP                  I
CI   35         I  „ - PEƒ“‹ŸTOP                  I
CI   36         I  ”A‡OBPA™ATE‹œ                   I
CI   37         I  KO‹‹EATE‹œHOE ‡BEHO            I
CI   38         I  HE‹ˆHE‰HOE ‡BEHO                I
CI   39         I  PE‹E‰HOE ‡BEHO                  I
CI   40         I  ‡BEHO "—ˆCTOE ‡AA‡„›BAHˆE"     I
CI   41         I  “MHO†ˆTE‹œ                      I
CI   42         I  ˆT“H                            I
CI   43         I  ˆH“H                            I
CI   44         I  ˆ„EA‹œH›‰ OEPA–ˆOHH›‰ “Cˆ‹ˆTE‹œI
CI   45         I  ‹EMEHT "ˆ"                     I
CI   46         I  ‹EMEHT "ˆ‹ˆ"                   I
CI   47         I  ‹EMEHT "ˆCK‹.ˆ‹ˆ"              I
CI   48         I  RS-TPˆƒƒEP                      I
CI   49         I   D-TPˆƒƒEP                      I
CI   50         I   T-TPˆƒƒEP                      I
CI   51         I  KOMAPATOP                      I
CI   52         I  „BˆƒATE‹œ OCTOŸHHOƒO TOKA      I
CI   53         I  3-X ”A‡H›‰ KOMEHCATOP          I
CI   54         I  KBA„PATH›‰ KOPEHœ               I
CI   55         I ƒEHEPATOP ˆ‹OOPA‡HOƒO CˆƒHA‹A  I
CI   56         I ˆH“T                             I
CI   57         I MˆKPOPO–ECCOP K1801BM1(2,3)     I
CI   58         I MEXAHˆ—ECKAŸ CˆCTEMA             I
CI   59         I œE‡O-KOMEHCATOP                I
CI              I                                  I
CI              I                                  I
CI              I                                  I
C+--------------+----------------------------------+
C Pˆ LTABNM = 5 E—ATœ ˆ‡ TABNM(IX) B ”OPMATE 5A4 [ 20 CˆMBO‹OB ]
C
C BXO„ O KOD_NAME :
C
C  IX = (KOD_NAME  -  1  ) * 5  + 1
C
CZZZ-------------------------------------------------------------------
         COMMON /SERVZ3/  TABTIP(300)
         DIMENSION TABTI1(50), TABTI2(50), TABTI3(50), TABTI4(50)
         DIMENSION TABTI5(50), TABTI6(50)
         EQUIVALENCE( TABTIP(1)  , TABTI1(1) )
         EQUIVALENCE( TABTIP(51) , TABTI2(1) )
         EQUIVALENCE( TABTIP(101), TABTI3(1) )
         EQUIVALENCE( TABTIP(151), TABTI4(1) )
         EQUIVALENCE( TABTIP(201), TABTI5(1) )
         EQUIVALENCE( TABTIP(251), TABTI6(1) )
C--->  HA  300 /  5  =  60  ˆMEH
         INTEGER TABTIP, TABTI1, TABTI2, TABTI3, TABTI4, TABTI5, TABTI6
C++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
        DATA  TABTI1/ 'COP', 'OTˆB', '‹EHˆ', 'E   ', '    ',
     2                'ˆH„“', 'KTˆB', 'HOCT', 'œ   ', '    ',
     3                'EMKO', 'CTœ ', '    ', '    ', '    ',
     4                'ˆCTO', '—HˆK', ' OC', 'T. T', 'OKA ',
     5                '.„.', 'C. ', 'OCTO', 'ŸHHA', 'Ÿ   ',
     6                '.„.', 'C. S', 'IN -', ' AŸ ', '    ',
     7                'RL_„', 'ˆO„ ', '    ', '    ', '    ',
     8                '„ˆO„', '    ', '    ', '    ', '    ',
     9                'BEHT', 'ˆ‹œ ', '    ', '    ', '    ',
     A                'MOCT', ' ‹AP', 'ˆOHO', 'BA  ', '    ' /
       DATA  TABTI2/  '‹. ', 'MA˜.', ' 3X3', 'X0  ', '    ',
     2                'RL_B', 'EHTˆ', '‹œ  ', '    ', '    ',
     3                '[??]', '[??]', '[??]', '[??]', '[??]',
     4                'ˆ„EA', '‹œH›', '‰ K‹', 'ž— -', 'PE‹E',
     5                'TPAH', 'C”OP', 'MATO', 'P   ', '    ',
     6                'HE‹ˆ', 'H. C', 'OPO', 'TˆB‹', 'EHˆE',
     7                'HE‹ˆ', 'H. ˆ', 'H„“K', 'TˆBH', 'OCTœ',
     8                'PEƒ.', ' BO‡', '“†.', ' 3X3', 'X0. ',
     9                'BO‡', '“„ˆT', 'E‹œ ', 'H—E', '-3”0',
     A                '„AT—', 'ˆK H', 'APŸ', '†EHˆ', 'Ÿ.  '  /
C
       DATA TABTI3/ '.„.', 'C. 3', '-ˆ ”', 'A‡› ', 'SIN.',
     2              '.„.', 'C. P', 'Eƒ. ', 'BO‡', '“†-Ÿ',
     3              'BEHT', 'ˆ‹œH', '›‰ K', '‹ž—-', '2_TP',
     4              'BEHT', 'ˆ‹œ,', ' “P', 'AB‹.', 'Cˆ”“',
     5              '˜AƒO', 'B›‰ ', '„Bˆƒ', 'ATE‹', 'œ.  ',
     6              '( Cˆ', '”“ )', '    ', '    ', '    ',
     7              'K‹ž—', ', “', 'PAB‹', 'ŸEM.', 'Cˆ”“',
     8              ' - ', 'PEƒ“', '‹ŸTO', 'P   ', '    ',
     9              'ˆ - ', 'PEƒ“', '‹ŸTO', 'P   ', '    ',
     A              'ˆHEP', '–ˆOH', 'HOE ', '‡BEH', 'O   ' /
       DATA TABTI4/ '„ - ', 'PEƒ“', '‹ŸTO', 'P   ', '    ',
     2              'ˆCTO', '—HˆK', ' SIN', ' TOK', 'A   ',
     3              'ˆCT.', 'TOKA', '“P.', 'O‹œ', '‡OB.',
     4              'ˆ -', 'PEƒ“', '‹ŸTO', 'P   ', '    ',
     5              '„ -', 'PEƒ“', '‹ŸTO', 'P   ', '    ',
     6              '”A‡O', 'BPA™', 'ATE‹', 'œ   ', '    ',
     7              'KO‹E', 'ATE', '‹œHO', 'E  ‡', 'BEHO',
     8              'HE‹ˆ', 'HE‰H', 'OE  ', '   ‡', 'BEHO',
     9              'PE‹E', '‰HOE', '    ', '   ‡', 'BEHO',
     A              '‡BEH', 'O "—', 'ˆCTO', 'E ‡A', '." ' /
       DATA TABTI5/ '“MHO', '†ˆTE', '‹œ  ', '    ', '    ',
     2              'ˆCT.', 'TOKA', ' “P', '.HA', 'P.  ',
     3              'ˆCT.', 'HAP', '.“P', '.HA', 'P.  ',
     4              'ˆ„EA', '‹œH›', '‰ O', '.“Cˆ', '‹ˆT.',
     5              '‹Oƒ.', '‹EM', 'EHT ', '"ˆ" ', '    ',
     6              '‹Oƒ.', '‹EM', 'EHT ', '"ˆ‹ˆ', '"   ',
     7              '‹Oƒ.', '‹EM', '."ˆC', 'K‹.ˆ', '‹ˆ" ',
     8              'RS -', 'TPˆƒ', 'ƒEP ', '    ', '    ',
     9              ' D -', 'TPˆƒ', 'ƒEP ', '    ', '    ',
     A              ' T -', 'TPˆƒ', 'ƒEP ', '    ', '    ' /
       DATA TABTI6/ 'KOM', 'APAT', 'OP  ', '    ', '    ',
     2              '„Bˆƒ', 'ATE‹', 'œ O', 'CT. ', 'TOKA',
     3              '3-X ', '”A‡H', '.KOM', 'EHC', 'ATOP',
     4              'KBA„', 'PATH', '›‰ K', 'OPEH', 'œ   ',
     5              'ƒEHE', 'PATO', 'P ˆ', '.Cˆƒ', 'HA‹A',
     6              'ˆH“T', '    ', '    ', '    ', '    ',
     7              'MˆK.', 'PO–', 'ECC.', ' K18', '01BM',
     8              'MEXA', 'Hˆ—E', 'CKAŸ', ' CˆC', 'TEMA',
     9              'œE‡', 'O-KO', 'MEH', 'CATO', 'P   ',
     A              '[??]', '[??]', '[??]', '[??]', '[??]' /
C++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
         END
