         SUBROUTINE DM0030 ( MSW, RMSW, YALL, JALL, LOGYTR,
     *                       TOKN, TOKN1, VALLN, VALLN1, KOD,
     *                       MSWALL, RMSWAL, ADRMSW )
CXXX----KOMèãEKC "MS1" --> BEPCàü 1.0  (OT ÑEKAÅPü 1986 É.)------------
C   èOÑèPOÉPAMMA:  DM0030 ( MSW, RMSW, YALL,       JALL, LOGYTR,
C   ------------             TOKN, TOKN1, VALLN, VALLN1, KOD,
C                            MSWALL, RMSWAL, ADRMSW )
CZZZ-------------------------------------------------------------------
         COMMON /PROF1/ MASPRT(200)
         COMMON /PROF2/ MACTAB(1)
         COMMON /PROF3/ FUNTAB(1)
         DIMENSION MSWALL(1), RMSWAL(1)
         DIMENSION MSW(1), RMSW(1), YALL(1), JALL(1), LOGYTR(1)
         DIMENSION VALLN(1), RMASPT(1), VALLN1(1), TOKN(1), TOKN1(1)
         RETURN
         END
