         SUBROUTINE FM0027( BA0T, KNOTT, PAR0T, RMSW, LM )
CXXX----KOMèãEKC "MS1" --> BEPCàü 1.0  (OT ÑEKAÅPü 1986 É.)------------
C
C
C   èOÑèPOÉPAMMA:  FM0027( BA0T, KNOTT, PAR0T, RMSW, LM )
C   ------------
CZZZ-------------------------------------------------------------------
         COMMON /PROF1/ MASPRT(200)
         DIMENSION BA0T(1), KNOTT(1), PAR0T(1), RMSW(1)
         INTEGER BA0T, TIP
         RETURN
         END
