* § £«ãèª¨.....
         subroutine me2n13
         write(*,*) ' ¥ç âì ¨§ ‡€ƒ‹“˜Šˆ ....... me2n13'
         return
         end
         subroutine me3n13
         write(*,*) ' ¥ç âì ¨§ ‡€ƒ‹“˜Šˆ ....... me3n13'
         return
         end
         subroutine me1n13
         write(*,*) ' ¥ç âì ¨§ ‡€ƒ‹“˜Šˆ ....... me1n13'
         return
         end
         subroutine chmove
         write(*,*) ' ¥ç âì ¨§ ‡€ƒ‹“˜Šˆ .......chmove '
         return
         end
         subroutine pagrz
         write(*,*) ' ¥ç âì ¨§ ‡€ƒ‹“˜Šˆ ...... pagrz '
         return
         end
         subroutine nekst
         write(*,*) ' ¥ç âì ¨§ ‡€ƒ‹“˜Šˆ ...... nekst '
         return
         end
         subroutine ome
         write(*,*) ' ¥ç âì ¨§ ‡€ƒ‹“˜Šˆ ...... ome '
         return
         end
         subroutine dvvvv
         write(*,*) ' ¥ç âì ¨§ ‡€ƒ‹“˜Šˆ ...... dvvvv '
         return
         end
         subroutine damatr
         write(*,*) ' ¥ç âì ¨§ ‡€ƒ‹“˜Šˆ ....... damatr'
         return
         end
         subroutine grav
         write(*,*) ' ¥ç âì ¨§ ‡€ƒ‹“˜Šˆ ....... grav'
         return
         end
         subroutine contrl
         write(*,*) ' ¥ç âì ¨§ ‡€ƒ‹“˜Šˆ ....... contrl'
         return
         end
         subroutine dsumma
         write(*,*) ' ¥ç âì ¨§ ‡€ƒ‹“˜Šˆ ....... dsumma'
         return
         end
         subroutine dapgrs
         write(*,*) ' ¥ç âì ¨§ ‡€ƒ‹“˜Šˆ ....... dapgrs'
         return
         end
         subroutine omts3
         write(*,*) ' ¥ç âì ¨§ ‡€ƒ‹“˜Šˆ ....... omts3'
         return
         end
         subroutine ymts3
         write(*,*) ' ¥ç âì ¨§ ‡€ƒ‹“˜Šˆ ....... ymts3'
         return
         end
         subroutine nmts3
         write(*,*) ' ¥ç âì ¨§ ‡€ƒ‹“˜Šˆ ....... nmts3'
         return
         end
*        subroutine mmts5
*        write(*,*) ' ¥ç âì ¨§ ‡€ƒ‹“˜Šˆ ....... mmts5'
*        return
*        end
*        subroutine mmts6
*        write(*,*) ' ¥ç âì ¨§ ‡€ƒ‹“˜Šˆ ....... mmts6'
*        return
*        end
         subroutine psub7
         write(*,*) ' ¥ç âì ¨§ ‡€ƒ‹“˜Šˆ ....... psub7'
         return
         end
